config/routes.rb
Rails.application.routes.draw do
  #get 'borrowings/new'

  # get 'sessions/new'

  # get 'borrowings/cretae' => "borrowings#create"
  
  get 'items/find_borrowing' => "items#find_borrowing"
  get 'items/found_item' => "items#found_item"
  get 'users/show_borrowing' => "users#show_borrowing"
  get 'items/item_ranking' => "items#item_ranking"
  get 'items/item_borrower_ranking' => "items#item_borrower_ranking"
  get 'items/item_category' => "items#item_category"

  root to: 'top_pages#home'
  get 'signup',  to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :items
  resources :borrowings
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  

    
    has_many :items
    has_many :borrowed_items, class_name: "Borrowing", foreign_key: "borrower_id", dependent: :destroy
    # has_many :borrowing_items, through: :borrowed_items, source: :item
    # has_many :borrowed_items, class_name: "Borrowing", foreign_key: "borrower_id", dependent: :destroy
    has_many :borrowing_items, through: :borrowed_items, source: :borrowed_item
    
  # アイテムを借りる
   def borrow(item)
    # borrowed_items.create(borrower_id: item.id)
    borrowed_items.create(borrowed_item_id: item.id)
    # borrowed_items.create(borrowed_item_id: item.id, start_day: date, end_day: date)
    # borrowed_items.create([{borrowed_item_id: item.id}, {start_day: date}, {end_day: date}])
   end
  
  # アイテムを返却する
  def item_return(item)
     borrowed_items.find_by(borrowed_item_id: item.id).destroy
  end
   
    # アイテムを借りているかどうか？
  def borrowing?(item)
    borrowing_items.include?(item)
  end
  
     #自分のアイテムかどうか？
#   def own_item(item)
#     current_user_items.include?(item)
#   end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
     @user = User.find(params[:id])
    # @items = @user.items
     @items = @user.items.page(params[:page])
     @borrowings = @user.borrowed_items
    # @borrowed_items = Borrowing.all
     @borrowed_items = Borrowing.group(:borrowed_item_id).order('count_borrowed_item_id desc').count(:borrowed_item_id).keys
      # binding.pry
     @items
  end

  
  def show_borrowing
    user_id = current_user.id
    @user = User.find(user_id)
    @items = @user.items
    # @borrowings = @user.borrowed_items
    @borrowings = @user.borrowed_items.page(params[:page])
  end

  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to TOKUSURU! ユーザー登録が完了しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path , notice: 'ユーザー情報を編集しました。'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
  def show
    @user = User.find(params[:id])
    @items = @user.items
  end
  
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="container-fluid">
    <div class="bg-info user_padding1">
        <h1>ユーザーアカウント編集</h1>
    </div>
    
    
    <div class="container-inner user_padding2">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 media-list"">
                <%= form_for(@user) do |f| %>
                    <%= render 'shared/error_messages', object: f.object %>
                    
                      <%= f.label :name %>
                      <%= f.text_field :name %>
        
                      <%= f.label :email %>
                      <%= f.text_field :email %>
                
                      <%= f.label :password %>
                      <%= f.password_field :password %>
                
                      <%= f.label :password_confirmation, "Confirmation" %>
                      <%= f.password_field :password_confirmation %>
        
                <%= f.submit "変更を保存", class: "btn btn-large btn-primary" %>
                <% end %>
                
                <div class="user_margin1">
                    <%= gravatar_for @user %>
                </div>
                <div class="user_margin1">
                    <a href="http://gravatar.com/emails">change</a>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
    <div class="">
      <div class="row">
          <div class="user_info">
            <h1>
              <%= gravatar_for @user %>
              <%= @user.name %>
            </h1>
          </div>
    </div>
    
    
    <div class="col-md-6 col-md-offset-3">
        <% if logged_in? %>
            <div class="center">
              <div><%= link_to "新規アイテムを登録", new_item_path, class: "btn btn-primary user_btn1" %></div>
              <div class="user_margin6 user_padding8"><%= link_to "現在借りているアイテムはこちら", users_show_borrowing_path %></div>
            </div>
            <div class="container-inner center">
              <div>
                <h3>登録されているモノ</h3>
              </div>
                <div class="#">
                    <%= page_entries_info @items %>
                </div>
                <div>
                    <%= paginate @items %>
                </div>
            </div>
            
        <% else %>
            <%= link_to "こちらからログインして下さい。", login_path %>
        <% end %>
        
    </div>
    
    <div class="container-inner user_padding2 user-bg-color">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <% if @user.items.any? && logged_in? %>
                  <div class="">
                    <ul class="user_margin8">
                      <%= render @items %>
                    </ul>
                  </div>
              <% else %>
              <% end %>
            </div>
        </div>
    </div>

    
    
        

</div>

app/views/users/show_borrowing.html.erb
<div class="container-fluid">
    <div class="">
          <div class="user_info">
            <h1>
              <%= gravatar_for @user %>
              <%= @user.name %>
            </h1>
          </div>
    </div>
    
    <div class="container-inner  user-bg-color">
      <div class="row">
          <div class="center">
           <div><%= link_to "新規アイテムを登録", new_item_path, class: "btn btn-primary user_btn1" %></div>
           <div class="user_margin6 user_padding8"><%= link_to "現在掲載中のアイテムはこちら", current_user %></div>
          </div>
            <div class="center">
                <h3>借りているモノ</h3>
                <div class="">
                    <%= page_entries_info @borrowings %>
                </div>
                <div>
                    <%= paginate @borrowings %>
                </div>
            </div>
            
            <div class="col-md-6 col-md-offset-3 user_padding2">
                <% if @borrowings.any? %>
                  
                  <% @borrowings.each do | item | %>
                      <% if item.borrowed_item_id != nil %>
                          <div class="media user_border2">
                            <% borrowing_item = Item.find(item.borrowed_item_id) %>
                           
                              <% if borrowing_item.avatar? %>
                                <div class="pull-left">
                                  <%= image_tag borrowing_item.avatar.thumb.url %>
                                </div>
                              <% else %>
                                <div class="pull-left">
                                  <%= image_tag("noimage.gif" ,  alt: "no-image") %>
                                </div>
                              <% end %>
                              <div class="media-body">
                                  <div>タイトル: <%= link_to borrowing_item.title, item_path(borrowing_item.id) %></div>
                                  <div>有効期間: <%= borrowing_item.start_day %> 〜 <%= borrowing_item.end_day %></div>
                                  <div class="user_margin10">
                                    <%= link_to "詳細", item_path(borrowing_item.id), class: "btn btn-large btn-primary" %>
                                  </div>
                                  <div class="user_margin10">
                                    <%= form_for(@borrowings.find_by(borrowed_item_id: item.borrowed_item_id),
                                    html: { method: :delete }) do |f| %>
                                    <%= f.submit "予約をキャンセル", class: "btn btn-danger" %>
                                    <% end %>
                                  </div>
                              </div>
                          </div>
                      <% else %>
                      <%# 何も表示しない %>
                      <% end %>
                  <% end %>
                <% end %>
          </div>
      </div>
        
        
   </div>
   
   
</div>