config/routes.rb
Rails.application.routes.draw do
  #get 'borrowings/new'

  # get 'sessions/new'

  # get 'borrowings/cretae' => "borrowings#create"
  
  get 'items/find_borrowing' => "items#find_borrowing"
  get 'items/found_item' => "items#found_item"
  get 'users/show_borrowing' => "users#show_borrowing"
  get 'items/item_ranking' => "items#item_ranking"
  get 'items/item_borrower_ranking' => "items#item_borrower_ranking"
  get 'items/item_category' => "items#item_category"

  root to: 'top_pages#home'
  get 'signup',  to: 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :items
  resources :borrowings
end

app/views/layouts/_categorylist.html.erb
<div class="container">
       <div id="category_list1" class="row user_padding4">
            <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_1.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c1", :method => :get) %>
                </div>
            </div>
            
             <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_2.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c2", :method => :get) %>
                </div>
            </div>
            
            <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_3.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c3", :method => :get) %>
                </div>
            </div>
            
            <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_4.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c4", :method => :get) %>
                </div>
            </div>
       </div>
       
       <div id="category_list2" class="row user_padding5">
            <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_5.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c5", :method => :get) %>
                </div>
            </div>
            
             <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_6.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c6", :method => :get) %>
                </div>
            </div>
            
            <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_7.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c7", :method => :get) %>
                </div>
            </div>
            
            <div class="col-lg-3 col-sm-6 col-md-4">
                <div class="user_category_list user_padding6">
                    <%= link_to image_tag("category_8.png", class: "img-responsive user_margin3", alt: "Responsive image" ), items_item_category_path(category: "c8", :method => :get) %>
                </div>
            </div>
       </div>
</div> 

app/views/layouts/_footer.html.erb
<footer class="user-footer">
        <div class="copyright text-center">&copy TOKUSURU</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">

    <!-- スマートフォンサイズで表示されるメニューボタンとテキスト -->
    <div class="navbar-header">

      <!-- 

        メニューボタン 
        
        data-toggle : ボタンを押したときにNavbarを開かせるために必要
        data-target : 複数navbarを作成する場合、ボタンとナビを紐づけるために必要

      -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-menu-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- タイトルなどのテキスト -->
      <a class="navbar-brand"><%= link_to "Tokusuru", root_path , id: "logo" %></a>

    </div>

    <!-- グローバルナビの中身 -->
    <div class="collapse navbar-collapse" id="nav-menu-1">
      
      <!-- 各ナビゲーションメニュー -->
      <ul class="nav navbar-nav">

        <!-- 通常のリンク -->
        <li class="active"><%= link_to "貸したい", items_path %></li>
        <li><%= link_to "借りたい", items_find_borrowing_path %></li>

        <!-- ドロップダウンのメニューも配置可能 -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">ランキング <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "貸したい", items_item_ranking_path %></li>
            <li class="divider"></li>
            <li><%= link_to "借りたい", items_item_borrower_ranking_path %></li>
          </ul>
        </li>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right user_right_margin1">
        <% if logged_in? %>
          <% #何も表示しない %>
          <% else %>
          <li><%= link_to "アカウント作成", signup_path %></li>
        <% end %>
        <% if logged_in? %>
          <!--<li><%#= link_to "ユーザー", '#' %></li>-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー情報", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>

    </div>
  </div>
</header>
<!--追加終了-->

app/views/layouts/_mainnav.html.erb
<nav class="navbar navbar-default" >
    <div class="container-fluid">
        <div class="navbar-header">
        <!--<nav class="navbar navbar-default navbar-static-top" >-->
            <div class="collapse navbar-collapse" id="collapse-target">
                <!--<div class="container">-->
                <ul  class="nav navbar-nav">
                <!--<ul class="user-navbar">-->
                    <li><%= link_to "サービス概要", '#' %></li>
                    <li><%= link_to "貸したい", items_path %></li>
                    <li><%= link_to "借りたい", items_find_borrowing_path %></li>
                    <li><%= link_to "ランキング", '#' %></li>
                    <li><%= link_to "よくある質問", '#' %></li> 
                <!--</ul>-->
                </ul>
            <!--</div>-->
            </div>
        </div>
    </div>



</nav>

<!--bg-primary-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tokusuru</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    <!--<div class="container">-->
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    <!--</div>-->
</body>
</html>